# Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

- A 0d tensor is a scalar,
- A 1d tensor is a vector (e.g. a sound sample),
- A 2d tensor is a matrix (e.g. a grayscale image),
- A 3d tensor can be seen as a vector of identically sized matrix (e.g. a
multi-channel image),
- A 4d tensor can be seen as a matrix of identically sized matrices, or a
sequence of 3d tensors (e.g. a sequence of multi-channel images),
- etc

There is a confusion between “dimension” for a vector in linear algebra, which is its number of coefficients, and “dimension” for a tensor, which is the number of indices to specify one of its coefficients. For instance an element of $\mathbb{R}^3$ is a three-dimension vector, but a one-dimension tensor.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing. Manipulating data through this constrained structure allows to use CPUs
and GPUs at peak performance.

For example, an RGB image of H rows and W columns of pixels can be encoded as a 3d tensor of size 3 × H × W, or depending on the convention H × W × 3.

A series of N images can thus be encoded as a
single tensor of size N × 3 × H × W.

### PyTorch’s main features are:
- Efficient tensor operations on CPU/GPU,
- automatic on-the-fly differentiation (autograd),
- optimizers,
- data I/O.

**“Efficient tensor operations”** encompass both standard linear algebra and, as we will see
later, deep-learning specific operations (convolution, pooling, etc.). A key specificity of PyTorch is the central role of **autograd** to compute derivatives of anything! (We will come back to this)

In [1]:
import torch
import numpy as np
torch.manual_seed(1234567) #fix the random seed (for the reproducability of your results)

## Tensor Initialization
Tensors can be initialized in various ways. Take a look at the following examples:

### Directly from data

Tensors can be created directly from data. The data type is automatically inferred.

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


### From a NumPy array

Tensors can be created from NumPy arrays (and vice versa - see [Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)).

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


### With pytorch

There are lots of options creating tensors using `torch.*`

`shape` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [4]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.6795, 0.0848, 0.9580],
        [0.8297, 0.0766, 0.4008]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### From another tensor:

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(x_ones)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.1517, 0.7493],
        [0.4604, 0.6330]])


### Back to scalars, lists, numpy arrays:
A 0d tensor can be converted back to a Python scalar with `.item()`. Any-dimensional tensors can be converted to lists by `.tolist()` or to NumPy arrays by `.numpy()`:

In [6]:
print(x_rand[0,0])
print(x_rand[0,0].item())
print(x_rand.tolist())
print(x_rand.numpy())

tensor(0.1517)
0.15170860290527344
[[0.15170860290527344, 0.7492750287055969], [0.46039390563964844, 0.6329887509346008]]
[[0.1517086  0.749275  ]
 [0.4603939  0.63298875]]


## Tensor Attributes

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [7]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


A tensor can be of many different data types. Take a look at the official documentation: [torch.tensor](https://pytorch.org/docs/stable/tensors.html), where you will find a large table of data types. The most important ones for now are:
- torch.float / torch.float32
- torch.long / torch.int64
- torch.bool

and their corresponding cuda variants.


In [8]:
t = torch.tensor([1,0,1,0,1])
print(t)
print(t.float())
print(t.bool())

tensor([1, 0, 1, 0, 1])
tensor([1., 0., 1., 0., 1.])
tensor([ True, False,  True, False,  True])


## Using the GPU

You can move tensors to the GPU, where many operations can be run (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU via `Runtime -> Change runtime type -> Hardware Accelerator -> GPU`. On Colab and linux-based systems, you can get GPU info by running `nvidia-smi`:

In [9]:
!nvidia-smi

Der Befehl "nvidia-smi" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.


In [10]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(tensor) # notice that the tensor's device is now 'cuda:X', with X indicating the gpu id

# Exercise: Working with Tensors
Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively described in the [pytorch docs](https://pytorch.org/docs/stable/torch.html). Many of them are similar to the numpy API.

### Simple Operations

Create a Tensor $ x = \begin{pmatrix} 1 & 2 &3 \\ 4 & 5 & 6 \end{pmatrix}$ and calculate the following:

In [11]:
x = 0
x = torch.tensor([[1,2,3],
                  [4,5,6]])

**a)** Sum over all entries:

In [12]:
x.sum()

tensor(21)

**b)** Sum only over dimension 1:

In [13]:
x.sum(dim=1)

tensor([ 6, 15])

**c)** Substract 1 from every element of $x$

In [14]:
x - 1

tensor([[0, 1, 2],
        [3, 4, 5]])

**d)** $x+x$:

In [15]:
x + x

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

**e)** Square $x$ elementwise:

In [16]:
x.pow(2)

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In-place operations are suffixed with an underscore:

In [17]:
x_test = torch.ones(2)
x_test.add_(4)
print(x_test)

tensor([5., 5.])


### Indexing and Slicing
You can apply standard NumPy indexing and Slicing to tensors.

In [18]:
x = torch.tensor(np.arange(16)).reshape(4,4)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]], dtype=torch.int32)


**a)** Print element $x_{2,1}$

In [19]:
print(x[2,1])

tensor(9, dtype=torch.int32)


**b)** Set all elements of column 1 to 0.

In [20]:
x[:, 1] = 0 # colon means select all from this dimension. here: all rows (dim=0), first column (dim=1)
print(x)

tensor([[ 0,  0,  2,  3],
        [ 4,  0,  6,  7],
        [ 8,  0, 10, 11],
        [12,  0, 14, 15]], dtype=torch.int32)


### Concatenation and Stacking of Tensors

In [21]:
x = torch.randint(0,6, (3,3))
print(x)

tensor([[4, 0, 5],
        [4, 5, 4],
        [3, 1, 2]])


**a)** Concatenate / Stack the tensor x multiple times to create a new tensor of shape (3, 9)

In [22]:
x_1 = torch.cat([x, x, x], dim=1)
print(x_1.shape)
print(x_1)

torch.Size([3, 9])
tensor([[4, 0, 5, 4, 0, 5, 4, 0, 5],
        [4, 5, 4, 4, 5, 4, 4, 5, 4],
        [3, 1, 2, 3, 1, 2, 3, 1, 2]])


**b)** Concatenate / Stack the tensor x multiple times to create a new tensor of shape (9, 3)

In [23]:
x_2 = torch.cat([x, x, x], dim=0)
print(x_2.shape)
print(x_2)

torch.Size([9, 3])
tensor([[4, 0, 5],
        [4, 5, 4],
        [3, 1, 2],
        [4, 0, 5],
        [4, 5, 4],
        [3, 1, 2],
        [4, 0, 5],
        [4, 5, 4],
        [3, 1, 2]])


**c)** Concatenate / Stack the tensor x multiple times to create a new tensor of shape (2, 3, 3)

In [24]:
x_3 = torch.stack([x, x], dim=0)
print(x_3.shape)
print(x_3)

torch.Size([2, 3, 3])
tensor([[[4, 0, 5],
         [4, 5, 4],
         [3, 1, 2]],

        [[4, 0, 5],
         [4, 5, 4],
         [3, 1, 2]]])


**d)** Concatenate / Stack the tensor x multiple times to create a new tensor of shape (3, 3, 2)

In [25]:
x_4 = torch.stack([x, x], dim=-1)
print(x_4.shape)
print(x_4)

torch.Size([3, 3, 2])
tensor([[[4, 4],
         [0, 0],
         [5, 5]],

        [[4, 4],
         [5, 5],
         [4, 4]],

        [[3, 3],
         [1, 1],
         [2, 2]]])


**e)** Concatenate / Stack the tensor x multiple times to create a new tensor of shape (3, 2, 3)

In [26]:
x_5 = torch.stack([x, x], dim=1)
print(x_5.shape)
print(x_5)

torch.Size([3, 2, 3])
tensor([[[4, 0, 5],
         [4, 0, 5]],

        [[4, 5, 4],
         [4, 5, 4]],

        [[3, 1, 2],
         [3, 1, 2]]])


### Multiplication of Tensors

In [27]:
x = torch.randint(0, 3, (3,2))
print(x)

tensor([[1, 1],
        [2, 0],
        [0, 0]])


**a)** Compute the elementwise product $x\cdot x$

In [28]:
print(x.mul(x)) # Alternative syntax: x*x

tensor([[1, 1],
        [4, 0],
        [0, 0]])


**b)** Compute the matrix multiplication $x x^T$

In [29]:
print(x.matmul(x.T)) # Alternative syntax: tensor @ tensor.T

tensor([[2, 2, 0],
        [2, 4, 0],
        [0, 0, 0]])


# Some Notes on Datatypes and Tensor Shapes

Some operations only work with specific datatypes. For example, computing the mean of a tensor cannot be executed on a int64 tensor:

In [30]:
torch.tensor([1,2,3,4,5,6]).mean()

RuntimeError: Can only calculate the mean of floating types. Got Long instead.

We can fix this by converting to floats:

In [31]:
torch.tensor([1,2,3,4,5,6]).float().mean()

tensor(3.5000)

Sometimes, a tensor does not have the shape we desire. `squeeze` and `unsqueeze` can help removing or adding dimensions:

In [32]:
t = torch.tensor([[1,2,3]])
print(t.shape)
print(t.unsqueeze(0).shape) # new dimension at location 0
print(t.squeeze(0).shape) # remove dimension at location 0

torch.Size([1, 3])
torch.Size([1, 1, 3])
torch.Size([3])


`view` or `reshape` can change the shape of a tensor:

In [33]:
print(t.view((3,1)).shape) # Note that view returns a "view on the tensor" (that means shared underlying memory),
print(t.reshape((3,1)).shape)          # while reshape can return a copy

torch.Size([3, 1])
torch.Size([3, 1])


Applying the sigmoid function:

In [34]:
torch.tensor([1,2,3]).sigmoid()

tensor([0.7311, 0.8808, 0.9526])

The is a very large number of tensor operations available. A full list is documented [here](https://pytorch.org/docs/stable/tensors.html). Whenever you want to perform some operation, we recommend you taking a look at this documentation and search through it to find what fits your needs. Overtime, you will feel more and more comfortable and remember many operations without having to look at the docs.

## Broadcasting
**Broadcasting** auto-magically expands dimensions by replicating coefficients, when it is necessary to perform operations that are “intuitively reasonable”. For example, it allows you to add a tensor $b$ of shape (3,) to a tensor $a$ of shape (2, 3) by replicating $b$ across the first dimension of $a$:


In [35]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
b = torch.tensor([1, 2, 3])
a.shape, b.shape, a + b

(torch.Size([2, 3]),
 torch.Size([3]),
 tensor([[2, 4, 6],
         [5, 7, 9]]))

While broadcasting can simplify many operations, it can also lead to unintended behavior and thus unnoticed bugs.
Try around with different shapes of a and b and different operations. We recommend to also at least skim read through the [documentation page of pytorch's Broadcasting semantics](https://pytorch.org/docs/stable/notes/broadcasting.html).